// Generated by Apple Swift version 2.0 (swiftlang-700.0.47.4 clang-700.0.59.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSError;
@class NSURLSessionDataTask;
@class NSMutableURLRequest;

SWIFT_CLASS("_TtC6Bridge8Endpoint")
@interface Endpoint : NSObject <NSCopying>

/// The route or relative path of your endpoint
@property (nonatomic, copy) NSString * __nonnull route;
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nullable params;
@property (nonatomic) NSInteger requestId;
@property (nonatomic, readonly, copy) void (^ __nullable successBlock)(id __nullable);
@property (nonatomic, readonly, copy) void (^ __nullable failureBlock)(NSError * __nullable);
@property (nonatomic, readonly, copy) NSString * __nullable tag;

/// Executes the request defined by this endpoint
///
/// \param id (optional) ID of the resource you wish to access
///
/// \param params (optional) dictionary of parameters to pass with this request
///
/// \param success closure with the code to be executed on success
///
/// \param failure closure with the code to be executed on failure
///
/// \returns  the <code>NSURLSessionDataTask
/// </code> which was executed
- (NSURLSessionDataTask * __nonnull)execute:(NSString * __nullable)id params:(NSDictionary<NSString *, id> * __nullable)params tag:(NSString * __nullable)tag success:(void (^ __nullable)(id __nullable))success failure:(void (^ __nullable)(NSError * __nullable))failure;

/// Endpoint specific request Bridges
///
/// \param requestBlock block
- (nonnull instancetype)before:(void (^ __nonnull)(Endpoint * __nonnull, NSMutableURLRequest * __nonnull))requestBlock;
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


SWIFT_CLASS("_TtC6Bridge6DELETE")
@interface DELETE : Endpoint
- (nonnull instancetype)init:(NSString * __nonnull)route OBJC_DESIGNATED_INITIALIZER;
@end



@interface Endpoint (SWIFT_EXTENSION(Bridge))
@end


@interface Endpoint (SWIFT_EXTENSION(Bridge))
@property (nonatomic, readonly, copy) NSString * __nonnull description;
@end


SWIFT_CLASS("_TtC6Bridge3GET")
@interface GET : Endpoint
- (nonnull instancetype)init:(NSString * __nonnull)route OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Bridge4POST")
@interface POST : Endpoint
- (nonnull instancetype)init:(NSString * __nonnull)route OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Bridge3PUT")
@interface PUT : Endpoint
- (nonnull instancetype)init:(NSString * __nonnull)route OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
